services:
  haos-one:
    build:
        context: ../../
        dockerfile: Dockerfile  
              
    privileged: true

    restart: unless-stopped

    ports:
      - "8123:8123"

    volumes:
      - hass-data:/mnt/data

    environment:
      - USE_DUMMY_NETWORKMANAGER=1

    stdin_open: true
    tty: true

volumes:
  hass-data:
